version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install
      - npm run build
  pre_build:
    commands:
      - echo "Testing for syntax errors"
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    commands:
      - echo "Running unittests"
      - pytest -v --cov
  post_build:
    commands:
      - echo "Tests run succesfully"