version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install
  build:
    commands:
      - echo "Running build"
      - npm run build
  post_build:
    commands:
      - echo "Tests run succesfully"
      - aws s3 sync build/ s3://pasi-react-bucket